# Generated by Django 3.0.8 on 2020-08-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('accepted', models.NullBooleanField()),
                ('competition', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=30)),
                ('value', models.FloatField()),
                ('offered_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('open', models.DateTimeField()),
                ('closed', models.DateTimeField()),
                ('minimum_capacity', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('verified', models.NullBooleanField()),
            ],
        ),
    ]
