# Generated by Django 4.1.4 on 2022-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='verified',
            field=models.BooleanField(null=True),
        ),
    ]
